### ISSUE TITLE
valuer error when using validate_lava.py

### ISSUE THREAD

**Issue by Ricardio609** [AngoraFuzzer/Angora#115]
what should I how to solve the error ?
command: 
`python3 validate_lava.py ~/Desktop/data/who/out_M/04082136 ~/Desktop/dataset/lava_corpus/LAVA-M/who/validated_bugs ~/Desktop/dataset/lava_corpus/LAVA-M/who/coreutils-8.24-lava-safe/lava-install/bin/who`
error:
```
/home/fuzz/Desktop/data/who/out_M/04082136/crashes/id:002167,sig:11,src:000233,op:havoc,rep:16: does not output bug id
[b'']
/home/fuzz/Desktop/data/who/out_M/04082136/crashes/id:003475,sig:11,src:000913,op:havoc,rep:4: does not output bug id
[b'']
/home/fuzz/Desktop/data/who/out_M/04082136/crashes/id:000033,sig:11,src:000004,op:havoc,rep:4: does not output bug id
[b'']
/home/fuzz/Desktop/data/who/out_M/04082136/crashes/id:003066,sig:11,src:000252,op:havoc,rep:32: does not output bug id
[b'']
Traceback (most recent call last):
  File "validate_lava.py", line 93, in <module>
    bugs_id = locate_crashes(crash_dirs, prom, flags, unique_dir)
  File "validate_lava.py", line 45, in locate_crashes
    cur_id = int(dot[27:])
ValueError: invalid literal for int() with base 10: b''
```

**Comment by spinpx** [comment]
Are you following https://github.com/AngoraFuzzer/Angora/blob/master/docs/lava.md#who ?
`who` won't output any bug ID in default, you should modify its code.

**Comment by Ricardio609** [comment]
@spinpx thanks. I have succeeded after modifying the source coe.
